### ISSUE TITLE
[BUG] Filtered Findings gives false green run

### ISSUE THREAD

**Issue by kaktusztea** [UmbrellaDocs/linkspector#85]
Hi,

linkspector worked very well, I like it very much, but recently it separates broken links (with anchor part) under "Filtered Findings" for some reason:
https://github.com/kaktusztea/km100/actions/runs/10962630450/job/30442347016

Action: [link](https://github.com/kaktusztea/km100/blob/master/.github/workflows/linkspector.yml)

.linkspector.yaml: [link](https://github.com/kaktusztea/km100/blob/master/.linkspector.yml)

So the workflow run is green although I have these broken links. I'd like the workflow to fail and notify me like before.

best regards,
kaktusztea

**Comment by gaurav-nelson** [comment]
Thank you @kaktusztea for creating the issue. This issue is related to [action-linkspector](https://github.com/UmbrellaDocs/action-linkspector) and not Linkspector. 

- To fix this, update your GitHub action YML configuration to include `filter-mode: nofilter`.

PS https://github.com/reviewdog/reviewdog?tab=readme-ov-file#filter-mode for more details.

**Comment by kaktusztea** [comment]
Thanks Gaurav!
